
export const actionTypes = {
  FIND_ALL_REQUEST: 'FIND_ALL_REQUEST',
  FIND_ALL_SUCCESS: 'FIND_ALL_SUCCESS',
  FIND_ALL_FAILURE: 'FIND_ALL_FAILURE',

  FIND_ONE_REQUEST: 'FIND_ONE_REQUEST',
  FIND_ONE_SUCCESS: 'FIND_ONE_SUCCESS',
  FIND_ONE_FAILURE: 'FIND_ONE_FAILURE',

  UPDATE_ONE_REQUEST: 'UPDATE_ONE_REQUEST',
  UPDATE_ONE_SUCCESS: 'UPDATE_ONE_SUCCESS',
  UPDATE_ONE_FAILURE: 'UPDATE_ONE_FAILURE',

  CREATE_ONE_REQUEST: 'CREATE_ONE_REQUEST',
  CREATE_ONE_SUCCESS: 'CREATE_ONE_SUCCESS',
  CREATE_ONE_FAILURE: 'CREATE_ONE_FAILURE',
}
